# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# grapes1.py
# Created on: 2014-11-03 17:06:42.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

# Check out any necessary licenses
arcpy.CheckOutExtension("3D")
arcpy.CheckOutExtension("spatial")


# Local directory variable - modify this to reflect your set up:
local_directory = "U:\\GIS_demos\\srtm_latest\\"

# Files:
srtm_34_02_tif = local_directory+"srtm_34_02.tif"
srtm_35_01_tif = local_directory+"srtm_35_01.tif"
srtm_35_02_tif = local_directory+"srtm_35_02.tif"
#srtm_latest = "U:\\GIS_demos\\srtm_latest"
Census2011_Province_Modified_shp = local_directory+"Census2011_Province_Modified.shp"
Census2011_Gaeltacht_Modified_shp = local_directory+"Census2011_Gaeltacht_Modified.shp"
srtm_combined = local_directory+srtm_combined"
srtm_29902 = local_directory+"srtm_29902"
srtm_clipped = local_directory+"srtm_clipped"
contour_50_shp = local_directory+"contour_50.shp"
hillshade__2_ = local_directory+"hillshade"
slope__2_ = local_directory+"slope"
Aspect__2_ = local_directory+"aspect"
Slope_r = local_directory+"slope_r"
Aspect_r = local_directory+"aspect_r"
Final_r = local_directory+"final_r"
Final_OK = local_directory+"final_ok"

# Process: Mosaic To New Raster
arcpy.MosaicToNewRaster_management(local_directory+"srtm_34_02.tif;U:\\GIS_demos\\srtm_latest\\srtm_35_01.tif;U:\\GIS_demos\\srtm_latest\\srtm_35_02.tif", srtm_latest, "srtm_combined", "GEOGCS['GCS_WGS_1984',DATUM['D_WGS_1984',SPHEROID['WGS_1984',6378137.0,298.257223563]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]]", "16_BIT_SIGNED", "", "1", "LAST", "FIRST")

# Process: Project Raster
arcpy.ProjectRaster_management(srtm_combined, srtm_29902, "PROJCS['TM65_Irish_Grid',GEOGCS['GCS_TM65',DATUM['D_TM65',SPHEROID['Airy_Modified',6377340.189,299.3249646]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]],PROJECTION['Transverse_Mercator'],PARAMETER['False_Easting',200000.0],PARAMETER['False_Northing',250000.0],PARAMETER['Central_Meridian',-8.0],PARAMETER['Scale_Factor',1.000035],PARAMETER['Latitude_Of_Origin',53.5],UNIT['Meter',1.0]]", "NEAREST", "", "", "", "")

# Process: Clip
arcpy.Clip_management(srtm_29902, "17491.1419994107 19589.9279998709 334558.590000137 466919.308999998", srtm_clipped, Census2011_Province_Modified_shp, "-32768", "NONE", "NO_MAINTAIN_EXTENT")

# Process: Contour
arcpy.Contour_3d(srtm_clipped, contour_50_shp, "100", "0", "1")

# Process: Hillshade
arcpy.gp.HillShade_sa(srtm_clipped, hillshade__2_, "315", "45", "NO_SHADOWS", "1")

# Process: Slope
arcpy.gp.Slope_sa(srtm_clipped, slope__2_, "DEGREE", "1")

# Process: Reclassify
arcpy.gp.Reclassify_sa(slope__2_, "Value", "20 45 1", Slope_r, "NODATA")

# Process: Aspect
arcpy.gp.Aspect_sa(srtm_clipped, Aspect__2_)

# Process: Reclassify (2)
arcpy.gp.Reclassify_sa(Aspect__2_, "Value", "160 200 1", Aspect_r, "NODATA")

# Process: Times
arcpy.gp.Times_sa(Slope_r, Aspect_r, Final_r)

# Process: Clip (2)
arcpy.Clip_management(Final_r, "17481.1949994104 19589.92799987 285663.314000014 448059.051000001", Final_OK, Census2011_Gaeltacht_Modified_shp, "-32768", "ClippingGeometry", "NO_MAINTAIN_EXTENT")

